apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream video_processors {
        server video-processor.default.svc.cluster.local:8080;
        keepalive 32;
      }

      server {
        listen 80;
        location / {
          proxy_pass http://video_processors;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
          proxy_next_upstream_tries 3;
          proxy_connect_timeout 5s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }

        location /health {
          access_log off;
          return 200 "healthy\n";
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
